// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace WpfAppSchoolDataBase.Models;

public partial class Course
{
    public int CourseID { get; set; }

    public string CourseCode { get; set; }

    public string CourseName { get; set; }

    public string Department { get; set; }

    public int Credits { get; set; }

    public virtual ICollection<StudentAdmission> StudentAdmissions { get; set; } = new List<StudentAdmission>();
}