// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace WpfAppSchoolDataBase.Models;

public partial class StudentAdmission
{
    public int StudentID { get; set; }

    public string FullName { get; set; }

    public string Gender { get; set; }

    public DateOnly DateOfBirth { get; set; }

    public string Email { get; set; }

    public string PhoneNum { get; set; }

    public string StreetAddress { get; set; }

    public string City { get; set; }

    public string StateProvince { get; set; }

    public string PostalCode { get; set; }

    public string PrevSchoolName { get; set; }

    public decimal GPA { get; set; }

    public int GraduationYear { get; set; }

    public int CourseID { get; set; }

    public DateOnly AdmissionDate { get; set; }

    public string ApplicationStatus { get; set; }

    public virtual Course Course { get; set; }
}